# Dockerfile.worker
FROM node:20-alpine

WORKDIR /app
COPY . .

RUN corepack enable && corepack prepare pnpm@latest --activate
RUN pnpm install --frozen-lockfile
RUN npx prisma generate

CMD ["pnpm", "run", "dev:worker"]
