version: "3.9"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "8081:8000"
    env_file:
      - .env
    depends_on:
      - valkey
      - qdrant
    volumes:
      - ./uploads:/app/uploads

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    env_file:
      - .env
    depends_on:
      - valkey
      - qdrant
    volumes:
      - ./uploads:/app/uploads

  valkey:
    image: valkey/valkey
    ports:
      - "6379:6379"

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
